export const Questions = [
    {
      id: 1,
      prompt: "Which of these is not a JavaScript framework?",
      optionA: "React",
      optionB: "Angular",
      optionC: "Vue",
      optionD: "Java",
      answer: "optionD",
    },
    {
      id: 2,
      prompt: "What does CSS stand for?",
      optionA: "Creative Style Sheets",
      optionB: "Computer Style Sheets",
      optionC: "Cascading Style Sheets",
      optionD: "Colorful Style Sheets",
      answer: "optionC",
    },
    {
      id: 3,
      prompt: "Which HTML tag is used to define an unordered list?",
      optionA: "<ol>",
      optionB: "<ul>",
      optionC: "<li>",
      optionD: "<list>",
      answer: "optionB",
    },
    {
      id: 4,
      prompt: "What is the correct way to comment out code in JavaScript?",
      optionA: "// This is a comment",
      optionB: "<!-- This is a comment -->",
      optionC: "/* This is a comment */",
      optionD: "# This is a comment",
      answer: "optionA",
    },
    {
      id: 5,
      prompt: "Which symbol is used for single-line comments in CSS?",
      optionA: "//",
      optionB: "/*",
      optionC: "#",
      optionD: "//",
      answer: "optionC",
    },
    {
      id: 6,
      prompt: "What does HTML stand for?",
      optionA: "Hyper Text Markup Language",
      optionB: "Hyperlinks and Text Markup Language",
      optionC: "Home Tool Markup Language",
      optionD: "Hyper Tool Markup Language",
      answer: "optionA",
    },
    {
      id: 7,
      prompt: "What is the correct way to include an external JavaScript file named 'script.js'?",
      optionA: "<script src='script.js'></script>",
      optionB: "<script href='script.js'></script>",
      optionC: "<script link='script.js'></script>",
      optionD: "<script file='script.js'></script>",
      answer: "optionA",
    },
    {
      id: 8,
      prompt: "Which CSS property is used to change the text color of an element?",
      optionA: "font-color",
      optionB: "text-color",
      optionC: "color",
      optionD: "text",
      answer: "optionC",
    },
    {
      id: 9,
      prompt: "Which of the following is NOT a valid data type in JavaScript?",
      optionA: "string",
      optionB: "boolean",
      optionC: "array",
      optionD: "object",
      answer: "optionC",
    },
    {
      id: 10,
      prompt: "How do you declare a variable in JavaScript?",
      optionA: "let myVar;",
      optionB: "variable myVar;",
      optionC: "myVar = var;",
      optionD: "var myVar;",
      answer: "optionD",
    },
  ];
  